name: mongo-sharding

services:
  mongos1:
    image: mongo:latest
    container_name: mongos_router_1
    restart: always
    ports:
      - "27020:27020"
    command: mongos --configdb config_server/configSrv:27017 --bind_ip_all --port 27020
    depends_on:
      - configSrv
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos2:
    image: mongo:latest
    container_name: mongos_router_2
    restart: always
    ports:
      - "27021:27021"
    command: mongos --configdb config_server/configSrv:27017 --bind_ip_all --port 27021
    depends_on:
      - configSrv
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  configSrv:
    image: mongo:latest
    container_name: configSrv 
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/db
    command: mongod --configsvr --replSet config_server --bind_ip_all --port 27017
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1:
    image: mongo:latest
    container_name: shard1
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - shard1-data:/data/db
    command: mongod --shardsvr --replSet shard1 --bind_ip_all --port 27018
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2:
    image: mongo:latest
    container_name: shard2
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - shard2-data:/data/db
    command: mongod --shardsvr --replSet shard2 --bind_ip_all --port 27019
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos1
      - mongos2
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: mongodb://mongos1:27020,mongos1:27021
      MONGODB_DATABASE_NAME: "somedb"
      
volumes:
  config-data:
  shard1-data:
  shard2-data: